import type { EventQualityScore, ExtensionRisk, MarketRegime, ProfitGrowthDriver, RejectionGateCode, RejectionGateResult, Swing10Component, Swing10Score, TradeQualityScore } from "@swing10/shared";
export const DEFAULT_SWING10_WEIGHTS:Record<Swing10Component,number>=Object.freeze({marketRegime:15,fundamentalEvent:15,trendRelativeStrength:15,momentum:10,candle:10,volume:10,entryQuality:25});
export const HARD_REJECTION_GATES=Object.freeze(["POOR_LIQUIDITY","STALE_DATA","INSUFFICIENT_DATA","LOW_RISK_REWARD","EXTREME_EXTENSION","FAILED_BREAKOUT","NEGATIVE_EVENT","HIGH_RISK_MARKET","ABNORMAL_SPREAD","NEARBY_MAJOR_RISK","LOW_CONFIDENCE_SOURCE"] as const);
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export interface EventQualityInput { revenueGrowthYoY:number|null;patGrowthYoY:number|null;ebitdaGrowthYoY:number|null;marginChangeBps:number|null;guidance:"UP"|"DOWN"|"UNCHANGED"|"UNKNOWN";profitGrowthDriver:ProfitGrowthDriver;sourceConfidence:number }
export function scoreEvent(i:EventQualityInput):EventQualityScore {let score=50;const reasons:EventQualityScore["reasons"]=[],missing:string[]=[];const add=(component:string,value:number,explanation:string,input:number|string|null)=>{score+=value;reasons.push({component,contribution:value,explanation,inputs:{value:input}})};for(const [name,value] of [["revenue",i.revenueGrowthYoY],["PAT",i.patGrowthYoY],["EBITDA",i.ebitdaGrowthYoY]] as const){if(value===null)missing.push(name);else add(name,Math.max(-12,Math.min(12,value/3)),`${name} growth contributes proportionally`,value);}if(i.marginChangeBps!==null)add("margin",Math.max(-10,Math.min(10,i.marginChangeBps/50)),"Margin change contribution",i.marginChangeBps);else missing.push("marginChangeBps");if(i.guidance==="UP")add("guidance",8,"Management guidance improved",i.guidance);if(i.guidance==="DOWN")add("guidance",-15,"Management guidance deteriorated",i.guidance);const penalties:Partial<Record<ProfitGrowthDriver,number>>={EXCEPTIONAL_INCOME:-18,ASSET_SALE:-18,TAX_BENEFIT:-14,ACCOUNTING_CHANGE:-18,LOW_BASE:-8,UNKNOWN:-5};if(penalties[i.profitGrowthDriver])add("profitQuality",penalties[i.profitGrowthDriver]!,`PAT quality adjusted for ${i.profitGrowthDriver}`,i.profitGrowthDriver);return{score:clamp(score),confidence:clamp(i.sourceConfidence*100-(missing.length*5)),profitGrowthDriver:i.profitGrowthDriver,reasons,missingInputs:missing};}
export interface ExtensionInput {returnSinceEventPercent:number;gapPercent:number;atrMove:number;distanceFromVwapPercent:number;distanceFromEma20Percent:number;rsi:number|null;volumeRatio:number;upperWickRatio:number;nearResistance:boolean}
export function assessExtension(i:ExtensionInput):{risk:ExtensionRisk;score:number;reasons:string[]}{let score=0;const reasons:string[]=[];const add=(v:number,r:string)=>{score+=v;reasons.push(r)};if(Math.abs(i.returnSinceEventPercent)>=8)add(40,"Move since event is at least 8%");else if(Math.abs(i.returnSinceEventPercent)>=4)add(20,"Move since event is at least 4%");if(i.atrMove>=3)add(25,"Move exceeds 3 ATR");if(Math.abs(i.distanceFromVwapPercent)>=4)add(15,"Price is far from VWAP");if(i.rsi!==null&&i.rsi>=78)add(10,"RSI is elevated");if(i.volumeRatio>=5)add(8,"Possible volume climax");if(i.upperWickRatio>=0.45)add(8,"Large upper wick");if(i.nearResistance)add(8,"Nearby resistance");score=Math.min(100,score);return{risk:score>=70?"EXTREME":score>=45?"HIGH":score>=20?"MEDIUM":"LOW",score,reasons};}
export interface RegimeInput {niftyTrend:number|null;bankNiftyTrend:number|null;vix:number|null;breadthPercent:number|null;sectorStrength:number|null}
export function assessMarketRegime(i:RegimeInput):MarketRegime {if(i.vix!==null&&i.vix>=25)return"HIGH_RISK";const available=[i.niftyTrend,i.bankNiftyTrend,i.breadthPercent===null?null:(i.breadthPercent-50)/10,i.sectorStrength].filter((v):v is number=>v!==null);if(available.length<2)return"NEUTRAL";const avg=available.reduce((a,b)=>a+b,0)/available.length;return avg>=1.5?"BULLISH":avg>=0.5?"MILD_BULLISH":avg<=-1.5?"BEARISH":avg<=-0.5?"MILD_BEARISH":"NEUTRAL";}
export interface TradeQualityInput {marketReaction:number;volume:number;vwap:number;trend:number;relativeStrength:number;breakout:number;levels:number;extension:number;regime:number;sector:number;liquidity:number;entryQuality:number;riskReward:number;overnightRisk:number}
export function scoreTrade(i:TradeQualityInput):TradeQualityScore {const weights:Record<keyof TradeQualityInput,number>={marketReaction:10,volume:9,vwap:8,trend:9,relativeStrength:8,breakout:7,levels:5,extension:10,regime:7,sector:4,liquidity:5,entryQuality:10,riskReward:6,overnightRisk:2};let score=0;const reasons:TradeQualityScore["reasons"]=[];for(const [component,weight] of Object.entries(weights) as [keyof TradeQualityInput,number][]){const raw=clamp(i[component]);const contribution=raw*weight/100;score+=contribution;reasons.push({component,contribution,explanation:`${component} weighted at ${weight}%`,inputs:{rawScore:raw}});}return{score:clamp(score),reasons,risks:[],missingInputs:[]};}
export function scoreSwing10(raw:Record<Swing10Component,number>,weights=DEFAULT_SWING10_WEIGHTS,version="swing10-v1"):Swing10Score{const total=Object.values(weights).reduce((a,b)=>a+b,0);if(total!==100)throw new Error(`SWING-10 weights must total 100, received ${total}`);let score=0;const components={} as Swing10Score["components"];for(const key of Object.keys(weights) as Swing10Component[]){const rawScore=clamp(raw[key]),weightedScore=rawScore*weights[key]/100;score+=weightedScore;components[key]={rawScore,weight:weights[key],weightedScore,explanation:`${key} contributes ${weightedScore.toFixed(2)} points`};}return{score:clamp(score),configurationVersion:version,components};}
export interface GateInput {liquid:boolean;fresh:boolean;sufficient:boolean;riskReward:number;extension:ExtensionRisk;failedBreakout:boolean;negativeEvent:boolean;regime:MarketRegime;spreadPercent:number;maxSpreadPercent:number;nearbyRisk:boolean;sourceConfidence:number;minSourceConfidence:number}
export function evaluateHardGates(i:GateInput):RejectionGateResult[]{const rows:Array<[RejectionGateCode,boolean,"REJECT"|"DOWNGRADE",unknown,unknown,string]>=[["POOR_LIQUIDITY",!i.liquid,"REJECT",i.liquid,true,"Liquidity requirement failed"],["STALE_DATA",!i.fresh,"REJECT",i.fresh,true,"Required market data is stale"],["INSUFFICIENT_DATA",!i.sufficient,"REJECT",i.sufficient,true,"Required inputs are unavailable"],["LOW_RISK_REWARD",i.riskReward<1.5,"REJECT",i.riskReward,1.5,"Risk/reward is below threshold"],["EXTREME_EXTENSION",i.extension==="EXTREME","REJECT",i.extension,"not EXTREME","Do not chase an extremely extended move"],["FAILED_BREAKOUT",i.failedBreakout,"REJECT",i.failedBreakout,false,"Breakout failed"],["NEGATIVE_EVENT",i.negativeEvent,"REJECT",i.negativeEvent,false,"Event is materially negative"],["HIGH_RISK_MARKET",i.regime==="HIGH_RISK","REJECT",i.regime,"not HIGH_RISK","Market regime blocks new paper buys"],["ABNORMAL_SPREAD",i.spreadPercent>i.maxSpreadPercent,"REJECT",i.spreadPercent,i.maxSpreadPercent,"Spread is abnormal"],["NEARBY_MAJOR_RISK",i.nearbyRisk,"DOWNGRADE",i.nearbyRisk,false,"Nearby event risk"],["LOW_CONFIDENCE_SOURCE",i.sourceConfidence<i.minSourceConfidence,"REJECT",i.sourceConfidence,i.minSourceConfidence,"Source confidence is too low"]];return rows.map(([code,triggered,severity,observedValue,threshold,explanation])=>({code,triggered,severity,observedValue:observedValue as number|string|boolean|null,threshold:threshold as number|string|boolean|null,explanation}));}
