import type { Candle } from "@swing10/shared";
const finite=(values:readonly number[])=>{if(!values.length||values.some(v=>!Number.isFinite(v)))throw new Error("Indicator input must contain finite values");};
export function sma(values:readonly number[],period:number):number|null{finite(values);if(period<1)throw new Error("Period must be positive");if(values.length<period)return null;return values.slice(-period).reduce((a,b)=>a+b,0)/period;}
export function ema(values:readonly number[],period:number):number|null{finite(values);if(period<1)throw new Error("Period must be positive");if(values.length<period)return null;const k=2/(period+1);let result=values.slice(0,period).reduce((a,b)=>a+b,0)/period;for(const v of values.slice(period))result=v*k+result*(1-k);return result;}
export function vwap(candles:readonly Candle[]):number|null{if(!candles.length)return null;let pv=0,volume=0;for(const c of candles){if(c.volume<0)throw new Error("Volume cannot be negative");const typical=(c.high+c.low+c.close)/3;pv+=typical*c.volume;volume+=c.volume;}return volume===0?null:pv/volume;}
export function rsi(values:readonly number[],period=14):number|null{finite(values);if(period<1)throw new Error("Period must be positive");if(values.length<=period)return null;let gains=0,losses=0;for(let i=1;i<=period;i++){const d=values[i]!-values[i-1]!;if(d>=0)gains+=d;else losses-=d;}let ag=gains/period,al=losses/period;for(let i=period+1;i<values.length;i++){const d=values[i]!-values[i-1]!,g=Math.max(d,0),l=Math.max(-d,0);ag=(ag*(period-1)+g)/period;al=(al*(period-1)+l)/period;}if(al===0)return ag===0?50:100;return 100-100/(1+ag/al);}
export function atr(candles:readonly Candle[],period=14):number|null{if(period<1)throw new Error("Period must be positive");if(candles.length<period+1)return null;const tr:number[]=[];for(let i=1;i<candles.length;i++){const c=candles[i]!,p=candles[i-1]!.close;tr.push(Math.max(c.high-c.low,Math.abs(c.high-p),Math.abs(c.low-p)));}let result=tr.slice(0,period).reduce((a,b)=>a+b,0)/period;for(const x of tr.slice(period))result=(result*(period-1)+x)/period;return result;}
export function volumeRatio(currentVolume:number,averageVolume:number):number|null{if(currentVolume<0||averageVolume<0)throw new Error("Volume cannot be negative");return averageVolume===0?null:currentVolume/averageVolume;}
export interface CandlePatterns {bullishEngulfing:boolean;bearishEngulfing:boolean;hammer:boolean;shootingStar:boolean;doji:boolean;insideBar:boolean;longUpperWick:boolean;longLowerWick:boolean;closeNearHigh:boolean;closeNearLow:boolean}
export function detectCandlePatterns(current:Candle,previous?:Candle):CandlePatterns{const range=current.high-current.low;if(range<=0)return{bullishEngulfing:false,bearishEngulfing:false,hammer:false,shootingStar:false,doji:true,insideBar:false,longUpperWick:false,longLowerWick:false,closeNearHigh:true,closeNearLow:true};const body=Math.abs(current.close-current.open),upper=current.high-Math.max(current.open,current.close),lower=Math.min(current.open,current.close)-current.low;return{bullishEngulfing:!!previous&&current.close>current.open&&previous.close<previous.open&&current.open<=previous.close&&current.close>=previous.open,bearishEngulfing:!!previous&&current.close<current.open&&previous.close>previous.open&&current.open>=previous.close&&current.close<=previous.open,hammer:lower>=body*2&&upper<=Math.max(body,.000001),shootingStar:upper>=body*2&&lower<=Math.max(body,.000001),doji:body/range<=0.1,insideBar:!!previous&&current.high<previous.high&&current.low>previous.low,longUpperWick:upper/range>=0.45,longLowerWick:lower/range>=0.45,closeNearHigh:(current.high-current.close)/range<=0.15,closeNearLow:(current.close-current.low)/range<=0.15};}
export function aggregateCandles(candles:readonly Candle[],minutes:5|15):Candle[]{if(!candles.length)return[];const buckets=new Map<number,Candle[]>();for(const candle of candles){const time=Date.parse(candle.exchangeTimestamp),bucket=Math.floor(time/(minutes*60_000))*(minutes*60_000);const list=buckets.get(bucket)??[];list.push(candle);buckets.set(bucket,list);}return[...buckets.entries()].sort(([a],[b])=>a-b).map(([time,rows])=>{const sorted=rows.sort((a,b)=>a.exchangeTimestamp.localeCompare(b.exchangeTimestamp)),first=sorted[0]!,last=sorted.at(-1)!;return{...first,timeframe:`${minutes}m` as Candle["timeframe"],exchangeTimestamp:new Date(time).toISOString(),localReceiveTimestamp:last.localReceiveTimestamp,open:first.open,high:Math.max(...rows.map(x=>x.high)),low:Math.min(...rows.map(x=>x.low)),close:last.close,volume:rows.reduce((a,b)=>a+b.volume,0)};});}
